# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.9.3LTS
group=com.cartoonishvillain.incapacitated

# Common
minecraft_version=1.20.1
mod_name=Incapacitated
mod_author=Mari (Cartoonish Villain)
mod_id=incapacitated
license=MIT
credits=Caltinor
description=Incapacitated allows players to be revived a small handful of times by other players before dying.
minecraft_version_range=[1.20.1, 1.20.2)

# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.15.11
cca_version = 5.2.2

# Forge
forge_version=49.0.22
forge_loader_version_range=[49,)
forge_version_range=[49,)

# NeoForge
neoforge_version=20.4.101-beta
neoforge_loader_version_range=[2,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
